# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
silent: true

vars:
  GIT_ROOT:
    sh: git rev-parse --show-toplevel

tasks:
  templ:
    desc: Run templ
    cmd: templ generate
